"""Type stubs for GenLayer SDK - Silences Pylance warnings"""

from typing import TypeVar, Generic, Callable, Any
from dataclasses import dataclass

# Type variables
K = TypeVar('K')
V = TypeVar('V')
T = TypeVar('T')

# Integer types
class u8(int):
    def __add__(self, other: Any) -> 'u8': ...
    def __sub__(self, other: Any) -> 'u8': ...
    
class u16(int):
    def __add__(self, other: Any) -> 'u16': ...
    def __sub__(self, other: Any) -> 'u16': ...
    
class u32(int):
    def __add__(self, other: Any) -> 'u32': ...
    def __sub__(self, other: Any) -> 'u32': ...
    
class u64(int):
    def __add__(self, other: Any) -> 'u64': ...
    def __sub__(self, other: Any) -> 'u64': ...
    
class u128(int):
    def __add__(self, other: Any) -> 'u128': ...
    def __sub__(self, other: Any) -> 'u128': ...
    
class u256(int):
    def __add__(self, other: Any) -> 'u256': ...
    def __sub__(self, other: Any) -> 'u256': ...
    def __mul__(self, other: Any) -> 'u256': ...
    def __truediv__(self, other: Any) -> 'u256': ...
    
class i8(int):
    def __add__(self, other: Any) -> 'i8': ...
    def __sub__(self, other: Any) -> 'i8': ...
    
class i16(int):
    def __add__(self, other: Any) -> 'i16': ...
    def __sub__(self, other: Any) -> 'i16': ...
    
class i32(int):
    def __add__(self, other: Any) -> 'i32': ...
    def __sub__(self, other: Any) -> 'i32': ...
    
class i64(int):
    def __add__(self, other: Any) -> 'i64': ...
    def __sub__(self, other: Any) -> 'i64': ...
    
class i128(int):
    def __add__(self, other: Any) -> 'i128': ...
    def __sub__(self, other: Any) -> 'i128': ...
    
class i256(int):
    def __add__(self, other: Any) -> 'i256': ...
    def __sub__(self, other: Any) -> 'i256': ...

# Address type
class Address(str): ...

# Collection types
class TreeMap(Generic[K, V], dict[K, V]): ...
class DynArray(Generic[T], list[T]): ...

# Decorators
def allow_storage(cls: type[T]) -> type[T]: ...

# GL module
class _Message:
    sender_address: Address
    value: u256

class _Block:
    number: u256
    timestamp: u256

class _Storage:
    @staticmethod
    def copy_to_memory(obj: T) -> T: ...
    
    @staticmethod
    def inmem_allocate(cls_: type[T], *args: Any, **kwargs: Any) -> T: ...

class _PublicView:
    def __call__(self, func: Callable) -> Callable: ...

class _PublicWrite:
    def __call__(self, func: Callable) -> Callable: ...
    
    @property
    def payable(self) -> _PublicView: ...

class _Public:
    view: _PublicView
    write: _PublicWrite

class _GL:
    message: _Message
    block: _Block
    storage: _Storage
    public: _Public
    
    class Contract:
        """Base class for GenLayer contracts"""
        ...
    
    @staticmethod
    def exec_prompt(prompt: str) -> str: ...
    
    @staticmethod
    def get_webpage(url: str, mode: str = 'text') -> str: ...
    
    @staticmethod
    def eq_principle_strict_eq(func: Callable[[], T]) -> T: ...

gl: _GL